---
title: "Iteration and Listcols"
output: github_document
date: "2024-10-25"
---

```{r}
library(tidyverse)
library(rvest)
```

## Here's some lists
printing "l" gives you the list of each thing
l[["mat"]][1, 3] --giving us matrix with 1st row 3rd column
```{r}
l=list(
  vec_numeric = 1:4,
  unif_sample= runif(100),
  mat=matrix(1:8, nrow=2, ncol=4, byrow=TRUE),
  summary=summary(rnorm(1000))
  
)
l

l$mat

l[["mat"]][1, 3]

l[[1]]
l[[4]]
```

Make a list that's hopefully a bit more useful.

```{r}
list_norm=
  list(
    a=rnorm(20, 0, 5 ),
    b=rnorm(20, 5, 5 ),
    c=rnorm(20, 0, 10 ),
    d=rnorm(20, 4, 10 )
  )

list_norm[["a"]]
list_norm[["b"]]

```

Let's reuse the function we wrote last time.

```{r}
mean_and_sd= function(x) {
  
  mean_x=mean(x)
  sd_x=sd(x)
  
  out_df=
    tibble(
      mean=mean_x,
      sd=sd_x
    )
  
  return(out_df)
  

}

```
Let's use the function to take mean and sd of all samples.

```{r}
mean_and_sd(list_norm[["a"]])
mean_and_sd(list_norm[["b"]])
mean_and_sd(list_norm[["c"]])
mean_and_sd(list_norm[["d"]])
```
same line of code copied and pasted over and over...

## Use a for loop

create output list, and run a for loop

```{r}
output= vector("list", length=4)

for (i in 1:4) {
  
  output[[i]]=mean_and_sd(list_norm[[i]])
  
}
output
```

